// server/sim/content/kits/waiguan/index.js — GENERATED by tools/gen-waiguan-kits.mjs: do not edit by hand.
// Every 外援 / 甄选 kit file (waiguan/char_*.js, `export default (bb, chess, def) => Kit`) registered for BOTH of its
// chess ids — chess_char_diy_5_<charId>_a and chess_char_diy_6_<charId>_a (elites `_b` resolve through their baseId).
// Static imports only: the Worker / replay-engine bundle (tools/build-worker.mjs) cannot follow a computed import().

import char_225_haak from './char_225_haak.js';

/** [charId, kit] in charId order. */
export const WAIGUAN_KITS = Object.freeze([
  ['char_225_haak', char_225_haak],
]);

const out = {};
for (const [charId, kit] of WAIGUAN_KITS) {
  out[`chess_char_diy_5_${charId}_a`] = kit;
  out[`chess_char_diy_6_${charId}_a`] = kit;
}
export default Object.freeze(out);
