// server/sim/content/kits/waiguan/index.js — GENERATED by tools/gen-waiguan-kits.mjs: do not edit by hand.
// Every 外援 / 甄选 kit file (waiguan/char_*.js, `export default (bb, chess, def) => Kit`) registered for BOTH of its
// chess ids — chess_char_diy_5_<charId>_a and chess_char_diy_6_<charId>_a (elites `_b` resolve through their baseId).
// Static imports only: the Worker / replay-engine bundle (tools/build-worker.mjs) cannot follow a computed import().

import char_003_kalts from './char_003_kalts.js';
import char_017_huang from './char_017_huang.js';
import char_112_siege from './char_112_siege.js';
import char_134_ifrit from './char_134_ifrit.js';
import char_197_poca from './char_197_poca.js';
import char_225_haak from './char_225_haak.js';
import char_322_lmlee from './char_322_lmlee.js';
import char_362_saga from './char_362_saga.js';
import char_456_ash from './char_456_ash.js';
import char_479_sleach from './char_479_sleach.js';
import char_608_acpion from './char_608_acpion.js';
import char_1048_orchd2 from './char_1048_orchd2.js';
import char_2014_nian from './char_2014_nian.js';
import char_2023_ling from './char_2023_ling.js';
import char_4228_closur from './char_4228_closur.js';

/** [charId, kit] in charId order. */
export const WAIGUAN_KITS = Object.freeze([
  ['char_003_kalts', char_003_kalts],
  ['char_017_huang', char_017_huang],
  ['char_112_siege', char_112_siege],
  ['char_134_ifrit', char_134_ifrit],
  ['char_197_poca', char_197_poca],
  ['char_225_haak', char_225_haak],
  ['char_322_lmlee', char_322_lmlee],
  ['char_362_saga', char_362_saga],
  ['char_456_ash', char_456_ash],
  ['char_479_sleach', char_479_sleach],
  ['char_608_acpion', char_608_acpion],
  ['char_1048_orchd2', char_1048_orchd2],
  ['char_2014_nian', char_2014_nian],
  ['char_2023_ling', char_2023_ling],
  ['char_4228_closur', char_4228_closur],
]);

const out = {};
for (const [charId, kit] of WAIGUAN_KITS) {
  out[`chess_char_diy_5_${charId}_a`] = kit;
  out[`chess_char_diy_6_${charId}_a`] = kit;
}
export default Object.freeze(out);
