# shellcheck shell=bash
# scripts/lib/deploy-common.sh — shared by scripts/deploy.sh (Docker Compose) and scripts/deploy-native.sh (systemd,
# no Docker): messages, settings file, logins, the Caddyfile and the summary. Sourced, never run.
#
# The caller sets before use:
#   DEPLOY ENV_FILE USERS_FILE CRED_FILE CADDY_DIR CADDYFILE PACK_DIR   paths (deploy/…)
#   ENV_KEYS            settings saved in $ENV_FILE (space separated)
#   CADDY_UPSTREAM      game server address for reverse_proxy (game:3000 / 127.0.0.1:3000)
#   CADDY_PACK_ROOT     the pack directory as Caddy sees it (/srv/pack / the absolute host path)
# and defines:
#   hash_password PW    → bcrypt hash on stdout
#   caddy_validate      → validates $CADDYFILE (prints Caddy's errors, non-zero when invalid)
#   caddy_site          → the site address (game.example.com / https://203.0.113.10)
#   caddy_global        → extra global option lines (may print nothing)
#   caddy_tls           → extra lines inside the site block, e.g. a tls { } block (may print nothing)
#   site_url            → the address players open (https://…/)
# Optional: ASSETS_ON_SERVER=1 when the game server hosts the art itself (the summary then says so).

if [ -t 1 ]; then B=$'\e[1m'; G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; N=$'\e[0m'; else B=; G=; Y=; R=; N=; fi
say()  { printf '%s\n' "${G}==>${N} $*"; }
warn() { printf '%s\n' "${Y}警告:${N} $*" >&2; }
die()  { printf '%s\n' "${R}错误:${N} $*" >&2; exit 1; }

YES=${YES:-0}
ask() { # ask "question" default(y|n) → 0 = yes
  local def=$2 a
  if [ "$YES" = 1 ] || [ ! -t 0 ]; then [ "$def" = y ]; return; fi
  read -r -p "$1 [$( [ "$def" = y ] && echo Y/n || echo y/N )] " a || a=
  a=${a:-$def}
  case "$a" in [Yy]*|是) return 0 ;; *) return 1 ;; esac
}

randhex() { od -An -N"$1" -tx1 /dev/urandom | tr -d ' \n'; }

# ---- settings ------------------------------------------------------------------------------------------------------

init_env() { local k; for k in $ENV_KEYS; do printf -v "$k" '%s' "${!k:-}"; done; }

load_env() {
  [ -f "$ENV_FILE" ] || return 0
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
}

save_env() {
  local k v
  mkdir -p "$DEPLOY"
  ( umask 077; : > "$ENV_FILE.tmp" )
  for k in $ENV_KEYS; do
    v=${!k}
    case "$v" in *"'"*|*$'\n'*) die "$k 不能包含单引号或换行：$v" ;; esac
    printf "%s='%s'\n" "$k" "$v" >> "$ENV_FILE.tmp"
  done
  mv "$ENV_FILE.tmp" "$ENV_FILE"
}

# ---- logins --------------------------------------------------------------------------------------------------------

valid_user() { [[ "$1" =~ ^[A-Za-z0-9._-]{1,32}$ ]] || die "用户名只能用字母、数字和 . _ -（最多 32 个字符）：$1"; }

add_user() { # add_user NAME → prints the password
  local name=$1 pw hash
  valid_user "$name"
  touch "$USERS_FILE"; chmod 600 "$USERS_FILE"
  if grep -q "^$name " "$USERS_FILE"; then warn "用户 $name 已存在，改为重置密码"; del_user_quiet "$name"; fi
  pw=$(randhex 10)
  hash=$(hash_password "$pw")
  [[ "$hash" == \$2* ]] || die "生成密码哈希失败"
  printf '%s %s\n' "$name" "$hash" >> "$USERS_FILE"
  ( umask 077; touch "$CRED_FILE" )
  grep -v "^$name " "$CRED_FILE" > "$CRED_FILE.tmp" || true
  printf '%s %s\n' "$name" "$pw" >> "$CRED_FILE.tmp"
  mv "$CRED_FILE.tmp" "$CRED_FILE"; chmod 600 "$CRED_FILE"
  printf '%s' "$pw"
}

del_user_quiet() {
  local f
  for f in "$USERS_FILE" "$CRED_FILE"; do
    [ -f "$f" ] || continue
    grep -v "^$1 " "$f" > "$f.tmp" || true
    mv "$f.tmp" "$f"; chmod 600 "$f"
  done
}

# ---- Caddyfile -----------------------------------------------------------------------------------------------------

write_caddyfile() {
  local tmp="$CADDYFILE.tmp" global
  mkdir -p "$CADDY_DIR"
  global=$(caddy_global)
  [ -n "$SP_EMAIL" ] && global=$(printf '\temail %s\n%s' "$SP_EMAIL" "$global")
  {
    echo "# Generated by scripts/$(basename "$0") — change the settings by re-running the script instead of editing this file."
    if [ -n "$global" ]; then printf '{\n%s\n}\n\n' "$global"; fi
    printf '%s {\n' "$(caddy_site)"
    caddy_tls
    printf '\tencode zstd gzip\n'
    printf '\troute {\n'
    case "$SP_AUTH" in
      basic)
        [ -s "$USERS_FILE" ] || die "basic 登录没有任何用户（add-user NAME）"
        printf '\t\tbasic_auth {\n'
        while read -r u h; do [ -n "$u" ] && printf '\t\t\t%s %s\n' "$u" "$h"; done < "$USERS_FILE"
        printf '\t\t}\n'
        ;;
      link)
        [ -n "$SP_LINK_KEY" ] || die "缺少邀请链接密钥"
        printf '\t\t@join path /join/%s\n' "$SP_LINK_KEY"
        printf '\t\thandle @join {\n'
        printf '\t\t\theader Set-Cookie "sp_key=%s; Path=/; Max-Age=31536000; HttpOnly; Secure; SameSite=Lax"\n' "$SP_LINK_KEY"
        printf '\t\t\tredir * / 302\n'
        printf '\t\t}\n'
        printf '\t\t@guest not header Cookie *sp_key=%s*\n' "$SP_LINK_KEY"
        printf '\t\trespond @guest "需要邀请链接才能进入 / Invite link required" 403\n'
        ;;
      none) ;;
      *) die "未知的登录方式：$SP_AUTH（basic | link | none）" ;;
    esac
    printf '\t\thandle_path /pack/* {\n'
    printf '\t\t\troot * %s\n' "$CADDY_PACK_ROOT"
    printf '\t\t\theader Cache-Control "public, max-age=604800"\n'
    printf '\t\t\tfile_server\n'
    printf '\t\t}\n'
    printf '\t\treverse_proxy %s\n' "$CADDY_UPSTREAM"
    printf '\t}\n'
    printf '}\n'
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$CADDYFILE"
  caddy_validate || die "生成的 Caddyfile 无效（上面是 Caddy 的报错）"
}

# ---- art pack sources ----------------------------------------------------------------------------------------------

asset_urls() { # SP_ASSET_URL from the hosted pack + the extra sources
  local urls= z
  if [ -f "$PACK_DIR/pack.json" ]; then urls="本站=/pack/"
  else
    z=$(find "$PACK_DIR" -maxdepth 1 -name '*.zip' -print -quit 2>/dev/null || true)
    [ -n "$z" ] && urls="本站=/pack/$(basename "$z")"
  fi
  [ -n "$SP_EXTRA_URLS" ] && urls="${urls:+$urls }$SP_EXTRA_URLS"
  SP_ASSET_URL=$urls
}

# ---- summary -------------------------------------------------------------------------------------------------------

print_access() {
  local cmd
  cmd="scripts/$(basename "$0")"
  echo
  echo "${B}游戏地址：${N} $(site_url)"
  case "$SP_AUTH" in
    basic)
      echo "${B}登录：${N} 浏览器会弹出用户名 / 密码框，输入一次后会记住。"
      if [ -s "$CRED_FILE" ]; then echo "  账号（$CRED_FILE）："; sed 's/^/    /' "$CRED_FILE"; fi
      echo "  加人：$cmd add-user 名字 · 删除：$cmd del-user 名字" ;;
    link)
      echo "${B}邀请链接：${N} $(site_url)join/$SP_LINK_KEY"
      echo "  朋友打开一次这个链接就能进（之后直接用游戏地址）。链接泄露了：$cmd new-link" ;;
    none) echo "${Y}没有登录保护：知道地址的人都能进来。${N}" ;;
  esac
  if [ "${ASSETS_ON_SERVER:-0}" = 1 ]; then echo "${B}素材：${N} 服务器自带全部素材，朋友打开网页就能玩，不需要导入。"
  elif [ -n "$SP_ASSET_URL" ]; then echo "${B}素材：${N} 玩家第一次进入时在浏览器里导入（来源：$SP_ASSET_URL）"
  else echo "${B}素材：${N} 服务器不提供下载源；把素材包 zip 发给朋友，在游戏的「导入素材包」里选择文件即可。"; fi
}
