#!/usr/bin/env node
// tools/doc-index.mjs — the table of contents of the long docs (docs/*.md: DESIGN.md alone is ~700 KB, too large to read
// whole), written to docs/context/DOC-INDEX.md: every heading with its line number and the size of its section, so a
// reader (a person or an agent) jumps straight to the section it needs (`sed -n '<from>,<to>p' docs/DESIGN.md`).
//
//   node tools/doc-index.mjs            regenerate docs/context/DOC-INDEX.md
//   node tools/doc-index.mjs --check    exit 1 when the committed index is stale (test/doc-index.test.js runs this)
//
// Headings inside fenced code blocks are skipped. Line numbers drift with every edit of a doc: regenerate after editing.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(ROOT, 'docs');
const OUT = path.join(DOCS, 'context', 'DOC-INDEX.md');

/** Headings of one Markdown text: { level, title, line } (1-based line), fenced code skipped. */
export function headings(text) {
  const out = [];
  let fence = null;
  text.split('\n').forEach((raw, i) => {
    const line = raw.replace(/\r$/, '');
    const f = /^\s*(```+|~~~+)/.exec(line);
    if (f) { fence = fence ? (line.trim().startsWith(fence) ? null : fence) : f[1]; return; }
    if (fence) return;
    const h = /^(#{1,4})\s+(.+?)\s*#*\s*$/.exec(line);
    if (h) out.push({ level: h[1].length, title: h[2], line: i + 1 });
  });
  return out;
}

const kb = (n) => (n >= 1024 ? `${(n / 1024).toFixed(n >= 10240 ? 0 : 1)} KB` : `${n} B`);

/** The index Markdown for the given docs ({ name, text }). */
export function buildIndex(docs) {
  const lines = [
    '# Doc index (generated)',
    '',
    'Generated by `node tools/doc-index.mjs` — do not edit by hand; regenerate after editing a doc (test/doc-index.test.js',
    'fails on a stale index). Each row: heading, line range, size of the section (up to the next heading of the same or a',
    "higher level). Read one section with `sed -n '<from>,<to>p' docs/<FILE>`.",
    '',
  ];
  for (const { name, text } of docs) {
    const rows = text.split('\n');
    if (text.endsWith('\n')) rows.pop(); // the empty string after the final newline is not a line
    const lineBytes = rows.map((r) => Buffer.byteLength(r, 'utf8') + 1);
    const hs = headings(text);
    lines.push(`## ${name} (${kb(Buffer.byteLength(text, 'utf8'))}, ${rows.length} lines)`, '');
    if (!hs.length) { lines.push('(no headings)', ''); continue; }
    lines.push('| Section | Lines | Size |', '|---|---|---|');
    hs.forEach((h, i) => {
      const next = hs.slice(i + 1).find((x) => x.level <= h.level);
      const to = next ? next.line - 1 : rows.length;
      let bytes = 0;
      for (let l = h.line - 1; l < to; l++) bytes += lineBytes[l] || 0;
      const title = h.title.replace(/\|/g, '\\|');
      lines.push(`| ${'&nbsp;&nbsp;'.repeat(h.level - 1)}${title} | ${h.line}–${to} | ${kb(bytes)} |`);
    });
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function readDocs() {
  return readdirSync(DOCS).filter((f) => f.endsWith('.md')).sort()
    .map((f) => ({ name: f, text: readFileSync(path.join(DOCS, f), 'utf8') }));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const want = buildIndex(readDocs());
  if (process.argv.includes('--check')) {
    let have = '';
    try { have = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
    if (have !== want) { console.error('docs/context/DOC-INDEX.md is stale: run `node tools/doc-index.mjs`'); process.exit(1); }
    console.log('docs/context/DOC-INDEX.md is current');
  } else {
    writeFileSync(OUT, want);
    console.log(`wrote ${path.relative(ROOT, OUT)}`);
  }
}
